//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_cuoc_dt
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaCuoc
    {
        public string MaGiaCuoc { get; set; }
        public Nullable<System.TimeSpan> TGBD { get; set; }
        public Nullable<System.TimeSpan> TGKT { get; set; }
        public Nullable<decimal> Giacuoc1 { get; set; }
    }
}
