//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_cuoc_dt
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTinhCuoc
    {
        public string MaHDTC { get; set; }
        public Nullable<int> IDSIM { get; set; }
        public Nullable<decimal> PhiHangThang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ThongTinSim ThongTinSim { get; set; }
    }
}
