//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_cuoc_dt
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDangKy
    {
        public string MaHDDK { get; set; }
        public Nullable<int> IDSIM { get; set; }
        public Nullable<decimal> ChiPhiDK { get; set; }
    
        public virtual ThongTinSim ThongTinSim { get; set; }
    }
}
