//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_cuoc_dt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSuDung
    {
        public int ID { get; set; }
        public Nullable<int> IDSIM { get; set; }
        public Nullable<System.DateTime> TGBD { get; set; }
        public Nullable<System.DateTime> TGKT { get; set; }
        public Nullable<decimal> SoPhut7h23h { get; set; }
        public Nullable<decimal> SoPhut23h7h { get; set; }
    
        public virtual ThongTinSim ThongTinSim { get; set; }
    }
}
