//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_cuoc_dt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLCuocDTEntities : DbContext
    {
        public QLCuocDTEntities()
            : base("name=QLCuocDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietSuDung> ChiTietSuDungs { get; set; }
        public virtual DbSet<GiaCuoc> GiaCuocs { get; set; }
        public virtual DbSet<HoaDonDangKy> HoaDonDangKies { get; set; }
        public virtual DbSet<HoaDonTinhCuoc> HoaDonTinhCuocs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<ThongTinSim> ThongTinSims { get; set; }
    
        public virtual ObjectResult<hienthi_Result> hienthi(string sdt, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("Ngaybd", ngaybd) :
                new ObjectParameter("Ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hienthi_Result>("hienthi", sdtParameter, ngaybdParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<Tinhcuoc_Result> tinhcuoc(string sdt, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("Ngaybd", ngaybd) :
                new ObjectParameter("Ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tinhcuoc_Result>("tinhcuoc", sdtParameter, ngaybdParameter, ngayktParameter);
        }
    }
}
